"""shipment bidding: status, expiry, bids, devices, user role

Revision ID: 435e3987290d
Revises: cb9ed9380261
Create Date: 2026-06-15 10:07:26.626522

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435e3987290d'
down_revision: str | None = 'cb9ed9380261'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_table('bids',
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('capitan_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='bidstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_bids_price_positive'),
    sa.ForeignKeyConstraint(['capitan_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bid_id'),
    sa.UniqueConstraint('shipment_id', 'capitan_id', name='uq_bids_shipment_capitan')
    )
    op.add_column('shipments', sa.Column('status', sa.Enum('pending', 'accepted', 'picked', 'out_for_delivery', 'delivered', 'expired', 'cancelled', name='shipmentstatus', native_enum=False, create_constraint=True), server_default='pending', nullable=False))
    op.add_column('shipments', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('shipments', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index('ix_shipments_open', 'shipments', ['created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index('ix_shipments_open', table_name='shipments', postgresql_where=sa.text("status = 'pending'"))
    op.alter_column('shipments', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('shipments', 'expires_at')
    op.drop_column('shipments', 'status')
    op.drop_table('bids')
    op.drop_table('devices')
    # ### end Alembic commands ###
